name: Deploy Website

on:
    push:
        branches: [ main ]
jobs:
    deploy:
        runs-on: ubuntu-linux
        steps:
        -   uses: actions/checkout@v2
        -   name: Set up Terraform
            uses: hashicorp/setup-terraform@v1
        -   name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: us-eas-1
        -   name: Terraform init
            run: cd terraform && terraform init
        
        -   name: Terraform apply
            run: cd terraform && terraform apply -auto-approve
        
        -   name: Get EC2 Public IP
            run: echo "EC2_PUBLIC_IP=$(cd terraform && terraform output -raw public_ip)" >> $GITHUB_ENV
        
        -   name: Deploy Website
            env:
                EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
            run:    |
                echo "$EC2_PRIVATE_KEY" > fedora.pub
                chmod 600 fedora.pub
                bash scripts/deploy.sh
            shell: bash
            
